In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("multiclass_data.csv")
df

,image_id,binary,multiclass,dataset,image_type,skin_tone,predicted_skin_tone,combined_skin_tone,stratify_col
0,000001.png,malignant,MEL,ddi,clinical,C,C,C,C_MEL_clinical
1,000002.png,malignant,MEL,ddi,clinical,C,C,C,C_MEL_clinical
2,000004.png,malignant,SCC,ddi,clinical,C,C,C,C_SCC_clinical
3,000005.png,malignant,BCC,ddi,clinical,A,B,A,A_BCC_clinical
4,000006.png,malignant,SCC,ddi,clinical,C,C,C,C_SCC_clinical
...,...,...,...,...,...,...,...,...,...
36092,Compound_Nevus_55_010271VB.jpg,benignant,NEV,sd_198,clinical,NaN,A,A,A_NEV_clinical
36093,Compound_Nevus_56_011095VB.jpg,benignant,NEV,sd_198,clinical,NaN,A,A,A_NEV_clinical
36094,Compound_Nevus_57_010690HB.jpg,benignant,NEV,sd_198,clinical,NaN,A,A,A_NEV_clinical
36095,Compound_Nevus_58_045672HB.jpg,benignant,NEV,sd_198,clinical,NaN,A,A,A_NEV_clinical
36096,Compound_Nevus_59_006100HB.jpg,benignant,NEV,sd_198,clinical,NaN,A,A,A_NEV_clinical

In [3]:
df.value_counts("dataset")

dataset
bcn          17157
ham           5053
derm12345     2883
fp            2590
pad           2298
derm7pt       1922
argentina     1502
isic_24       1045
sd_198         732
scin           402
ddi            343
med_node       170
Name: count, dtype: int64

In [8]:
#get skin tone distribution by dataset
for dataset in set(df.value_counts('dataset').keys()):
    print(dataset)
    dataset_df = df[df['dataset']==dataset]
    #print(dataset_df.value_counts('combined_skin_tone'))
    print(dataset_df.value_counts('skin_tone'))
    print()

ddi
skin_tone
B    154
A    123
C     66
Name: count, dtype: int64

argentina
skin_tone
A    1113
B     259
Name: count, dtype: int64

fp
skin_tone
A    1444
B     920
C     226
Name: count, dtype: int64

scin
skin_tone
A    199
B    119
C     19
Name: count, dtype: int64

derm7pt
Series([], Name: count, dtype: int64)

ham
Series([], Name: count, dtype: int64)

med_node
Series([], Name: count, dtype: int64)

derm12345
Series([], Name: count, dtype: int64)

bcn
Series([], Name: count, dtype: int64)

pad
skin_tone
A    1029
B     454
C      11
Name: count, dtype: int64

isic_24
Series([], Name: count, dtype: int64)

sd_198
Series([], Name: count, dtype: int64)