In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("skin_tone_data.csv")
df

,image_id,binary,multiclass,skin_tone,dataset,image_type,stratify_col
0,000001.png,malignant,MEL,C,ddi,clinical,C_clinical
1,000002.png,malignant,MEL,C,ddi,clinical,C_clinical
2,000003.png,NaN,NaN,C,ddi,clinical,C_clinical
3,000004.png,malignant,SCC,C,ddi,clinical,C_clinical
4,000005.png,malignant,BCC,A,ddi,clinical,A_clinical
...,...,...,...,...,...,...,...
32354,ISIC_9988844.jpg,benignant,NEV,A,argentina,dermatoscopic,A_dermatoscopic
32355,ISIC_9995847.jpg,NaN,NaN,A,argentina,dermatoscopic,A_dermatoscopic
32356,ISIC_9997367.jpg,benignant,ACK,A,argentina,clinical,A_clinical
32357,ISIC_9998679.jpg,malignant,BCC,A,argentina,dermatoscopic,A_dermatoscopic
32358,ISIC_9999251.jpg,benignant,ACK,A,argentina,dermatoscopic,A_dermatoscopic

In [3]:
df.value_counts("dataset")

dataset
fp           15956
scin          8683
mskcc         4096
pad           1494
argentina     1474
ddi            656
Name: count, dtype: int64

In [4]:
df_deduplicated = df.drop_duplicates(subset=['image_id'])
df_deduplicated

,image_id,binary,multiclass,skin_tone,dataset,image_type,stratify_col
0,000001.png,malignant,MEL,C,ddi,clinical,C_clinical
1,000002.png,malignant,MEL,C,ddi,clinical,C_clinical
2,000003.png,NaN,NaN,C,ddi,clinical,C_clinical
3,000004.png,malignant,SCC,C,ddi,clinical,C_clinical
4,000005.png,malignant,BCC,A,ddi,clinical,A_clinical
...,...,...,...,...,...,...,...
32354,ISIC_9988844.jpg,benignant,NEV,A,argentina,dermatoscopic,A_dermatoscopic
32355,ISIC_9995847.jpg,NaN,NaN,A,argentina,dermatoscopic,A_dermatoscopic
32356,ISIC_9997367.jpg,benignant,ACK,A,argentina,clinical,A_clinical
32357,ISIC_9998679.jpg,malignant,BCC,A,argentina,dermatoscopic,A_dermatoscopic
32358,ISIC_9999251.jpg,benignant,ACK,A,argentina,dermatoscopic,A_dermatoscopic

In [5]:
df_deduplicated.value_counts("dataset")

dataset
fp           15956
scin          4180
mskcc         4096
pad           1494
argentina     1474
ddi            656
Name: count, dtype: int64